version: '3.8'

services:
  app:
    build: .
    container_name: task_manager_app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: "postgresql://username:password@db:5432/task_manager"
      REDIS_URL: "redis://redis:6379"
    volumes:
      - .:/var/www
    restart: always

  db:
    image: postgres:15
    container_name: task_manager_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:6.0
    container_name: task_manager_redis
    ports:
      - "6379:6379"
    restart: always
